### ISSUE TITLE
P3D Support in p5py

### ISSUE THREAD

**Issue by parsoyaarihant** [p5py/p5#112]
TODO:

- [x]  Create 3D renderer for p5py
- [x] Add support for `camera` and 3D transforms
- [x] Implement 3D primitives: `plane` , `box`, `sphere` and `curves`
- [x] Different light sources and lighting models.

**Comment by jeremydouglass** [comment]
When this says "Create" a 3D renderer -- does it mean building on OpenGL, e.g. pyOpenGL or related?

-  http://pyopengl.sourceforge.net/
-  http://www.labri.fr/perso/nrougier/python-opengl/

Or does it mean creating one from scratch?

**Comment by parsoyaarihant** [comment]
By "Create" I meant building it on top of `vispy`(the python graphic library being used by p5.py)

**Comment by mak-simgithub** [comment]
Hey guys, do the checked boxes in front of items 1 to 3 mean these features have already been implemented? If so, how can I use them? Thanks for your effort!

**Comment by parsoyaarihant** [comment]
@mak-simgithub , the above is implemented but there are a few bugs which needs to be fixed before it becomes usable: https://github.com/p5py/p5/issues/152
