### ISSUE TITLE
Rectangle not overlaying on line correctly

### ISSUE THREAD

**Issue by parsoyaarihant** [p5py/p5#114]
Drawing a rectangle over a line does not fully obscure the line

**To Reproduce**
```python
from p5 import *

def setup():
	size(640, 360)
	no_loop()

def draw():
	background(0)
	stroke(255)
	line((0, 0), (200, 200))
	fill(255, 0, 0)
	rect((60, 50), 50, 50)

if __name__ == '__main__':
	run()
```

**Output**
<img width="640" alt="Screenshot 2019-06-04 at 3 04 41 PM" src="https://user-images.githubusercontent.com/15258498/58868493-154ef780-86da-11e9-844b-5961d8e7c1e5.png">

I believe the problem is in the renderer. The renderer first renders all the polygons before lines.  Reference: https://github.com/p5py/p5/blob/master/p5/sketch/renderer.py#L276

**System information:**
 - p5 release (version number or latest commit):
 - Python version: 3.7
 - Operating system: MacOS Mojave

**Comment by abhikpal** [comment]
This looks like #67.

**Comment by jeremydouglass** [comment]
A guess (not an OpenGL expert) is that you need to get rid of globals poly_draw_queue, line_draw_queue, point_draw_queue and replace them with a single `draw_queue`.

So, in add_to_draw, append like this this:

        draw_queue.append(('poly', vertices, idx, fill))
        draw_queue.append(('point', vertices, idx, stroke))
        draw_queue.append(('line', vertices, idx, stroke))

...and then flush_geometry needs to iterate over that existing labeled queue  -- rather than building it manually with zip() out of three small queues.

**Comment by parsoyaarihant** [comment]
When we use a common draw_queue, OpenGL is called multiple times whenever the opengl primitives (triangles, lines, triangles) change. This makes the overall efficiency of code slower. Hence, this structure was adopted. 

In the current development branch, we have implemented a common `draw_queue` with some performance optimisation. It will be merged into the main code soon.
