### ISSUE TITLE
Interactivity Tutorials The key variable stores example raise ValueError("text_size is nor supported for Bitmap Fonts") 

### ISSUE THREAD

**Issue by edurojasr** [p5py/p5#126]
**Describe the bug**
The following example, within the Interactivity tutorials when running, the following error occurs

In the Interactivity Tutorial in Keyboard data section the next example

    from p5 import *

    def setup():
        size(100, 100)
        text_size(60)

    def draw():
        background(0)
        text(key, 20, 75) # Draw at coordinate (20,75)

    if __name__ == '__main__':
        run()

when run shows the fallowing error:  
raise ValueError("text_size is nor supported for Bitmap Fonts")

**To Reproduce**
Just copy and paste the example in a text editor and run the script

**Expected behavior**
Should show in the window the key pressed in a specify size 

**Screenshots**
![p5 error](https://user-images.githubusercontent.com/35645729/64573701-85989500-d329-11e9-8646-d8318360926b.png)

**System information:**
 - p5 release (0.6.0):
 - Python version: 3.7.4
 - Operating system: Windows 10

**Additional context**
Changing the script to 

    from p5 import *

 
    def setup():
        size(150, 150)
       # text_size(60) need to comment this line

    def draw():
        background(0)
        text(str(key), (20, 75))  # add str() to key

    run()

Give me the next result: 

![p5 error 2](https://user-images.githubusercontent.com/35645729/64574164-9813ce00-d32b-11e9-81b2-3a1716af3304.png)

Key NOT pressed:

![key_not_pressed](https://user-images.githubusercontent.com/35645729/64574177-a4982680-d32b-11e9-8d12-859cb67acf4f.png)

Key pressed:
![key_pressed](https://user-images.githubusercontent.com/35645729/64574191-ac57cb00-d32b-11e9-8b46-674bee6dba31.png)

So as you can see, a get a similar behavior expected from the example with this changes, but I don't know if this is a real fix or its something else under the hood

**Comment by edurojasr** [comment]
#116 As I can see know apparently text_size is not yet implemented.
Should an example be created that has a behavior similar to the example but using only what is implemented? like my work around but better Or does the example remain the same until the text_size is implemented?

we could put in the tutorials a notice about what is implemented and what is not

**Comment by parsoyaarihant** [comment]
the function `text_size`  is implemented but not for bitmap fonts. The default font loaded in by p5 is bitmap hence you are experiencing the error. Try loading `.otf` or `.ttf`  fonts.

**Comment by edurojasr** [comment]
should the documentation reflect that? I could clarify the example and indicate the situation. what is your documentation strategy with the tutorials? Sorry if you had already mentioned this, but I would like to help with this if you let me.

**Comment by parsoyaarihant** [comment]
What we can do is change the default font from bitmap to a `.otf` or `.ttf` font which will resolve this issue and make it convenient for most users.

**Comment by edurojasr** [comment]
That would be great! just out of curiosity, why is the current default bitmap?

**Comment by parsoyaarihant** [comment]
> why is the current default bitmap?

The PIL library which p5py uses provides a bitmap font by [default](https://github.com/p5py/p5/blob/master/p5/core/font.py#L35).

**Comment by edurojasr** [comment]
oh I see, so its not something that Processing have by default

**Comment by jeremydouglass** [comment]
In Processing / PDE, I believe the default font is the bundled JRE default font:

https://forum.processing.org/one/topic/finding-default-font.html

...and in Java 8, that is Lucida: https://docs.oracle.com/javase/8/docs/technotes/guides/intl/font.html

I'm not sure what font p5.js uses as a default, but it might be the browser built-in.

> What we can do is change the default font from bitmap to a .otf or .ttf font which will resolve this issue and make it convenient for most users.

This seems like a good idea. Perhaps choose an open source unicode typeface with an appropriate license and bundle it?

https://en.wikipedia.org/wiki/Open-source_Unicode_typefaces

The advantage of a unicode font -- for example, Noto -- is that it is useful out of the box to a broad multilingual community.

**Comment by edurojasr** [comment]
Looks great and makes the text and strings functions and examples much easier to use

**Comment by Haksell** [comment]
I see this issue is still open and I don't feel like opening an issue just for that but the message says "ValueError: text_size is **nor** supported for Bitmap Fonts" instead of **not**.

**Comment by jeremydouglass** [comment]
> ValueError: text_size is **nor** supported for Bitmap Fonts

https://github.com/p5py/p5/blob/63dac5bd2a2a4c99650f7afb66527fe3fb2de084/p5/core/font.py#L229

**Comment by vrruiz** [comment]
> What we can do is change the default font from bitmap to a `.otf` or `.ttf` font which will resolve this issue and make it convenient for most users.

I just hit this error. This would be very helpful, indeed, specially for users without advanced knowledge.

**Comment by vbartle** [comment]
looks like this was already explained above but for those looking for a solution I was able to do: ``text_font(create_font('handwriting.ttf', size=100))```
