### ISSUE TITLE
[Feature request] Make windows resizabe and launch a resize event

### ISSUE THREAD

**Issue by swirly** [p5py/p5#132]
In P5js, you can resize the navigator windows, and it launches a resize event that can be catched by the script

It should be interesting to have such a behavior, instead of the inability to resize the windows that is hardcoded.

**Comment by define-private-public** [comment]
Has anyone made any work on this yet?  I'm interested in having it available.

**Comment by parsoyaarihant** [comment]
I am a bit occupied right now. I will try to implement it by this weekend.

**Comment by parsoyaarihant** [comment]
I have implemented the support to resize the canvas using mouse. Every time the canvas is resized, the variables `width` and `height` are updated.
