### ISSUE TITLE
"RuntimeError: Could not import backend "Glfw": GLFW library not found"

### ISSUE THREAD

**Issue by Maxdede** [p5py/p5#133]
Hello,

i need to use p5 but it doesn't work
when i try "from p5 import *", the console answer "RuntimeError: Could not import backend "Glfw":
GLFW library not found"
I already try what you can find on https://github.com/p5py/p5/issues/76
i'm on windows, i use Spyder and Python 3.7
I'm new in Computer Science so be nice with me please

Thanks

**Comment by kylepollina** [comment]
Have you followed every step of dbhavsar76's recommendations? It is fairly detailed. Are you having any issues with installing GLFW and setting the PATH variable?

**Comment by Maxdede** [comment]
I followed his recommendations step by step only once finished, encountered no problem by installing GLFW or setting the PATH but the problem was still there.
This may be because I am using Spyder instead of python-3.7.1-amd64.exe
I have all uninstall and install python-3.7.1-amd64.exe
however, I have a problem with the installation of p5 and can not find any solution on the internet (there may be some but I have not found)
I have attached the photo of my problem, I am sorry in advance if it is trivial but as a novice, all this exceeds me
thank you for your understanding
![Python](https://user-images.githubusercontent.com/56837735/67672882-21816d00-f979-11e9-94e7-f6cac9bbbbac.PNG)

**Comment by dbhavsar76** [comment]
You are running the command in python shell in the screenshot, while pip is separate utility. So you need to run it in normal console.
ie. open cmd, run `pip install p5`
that is assuming that your Path is properly set to pip

**Comment by Maxdede** [comment]
the problem came from the pip PATH
I finally managed to use p5 by following the steps of dbhavsar7
Thank you for your help
