### ISSUE TITLE
p5 live (interactive) sketching through python REPL

### ISSUE THREAD

**Issue by d-01** [p5py/p5#139]
There is a demo of live sketching with `p5` through python REPL in this article: [link](https://medium.com/processing-foundation/p5-a-python-implementation-of-the-processing-api-5f05c62db23b).
![live sketching demo](https://miro.medium.com/max/960/1*QJGl5JXr45zsvevMFXLQjQ.gif)
Is it possible with the current version or downgrading is the only option if one wants to reproduce functionality shown?
In current version (`pip list` shows `p5 → 0.6.0`) no windows appear after `from p5 import *`.
After `run()` command window appears, but blocks python shell.

**Comment by abhikpal** [comment]
This was part of a an earlier prototype. This functionality is no longer available in the current version.
