### ISSUE TITLE
Loooong install error

### ISSUE THREAD

**Issue by Lightosk** [p5py/p5#144]
**Describe the bug**
I get a loooong error when trying to install p5 via `pip install p5`.

**To Reproduce**
Don't know why this is only appearing to me.

**Expected behavior**
To get p5 installed properly

**System information:**
 - p5 release (version number or latest commit):
 - Python version: 3.8.0
 - Operating system: Microsoft Windows [Version 10.0.18363.657]
[error.txt](https://github.com/p5py/p5/files/4231345/error.txt)

**Additional context**
I have cygwin64 and Visual Studio installed.

**Comment by Lightosk** [comment]
I THINK found the solution. In this part:
```ERROR: Command errored out with exit status 1: 'C:\Users\Laptop\AppData\Local\Programs\Python\Python38\python.exe' 'C:\Users\Laptop\AppData\Local\Programs\Python\Python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Laptop\AppData\Local\Temp\pip-build-env-6ohp2kl7\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel 'setuptools>=30.3.0' setuptools_scm setuptools_scm_git_archive 'Cython>=0.29.2' 'numpy; python_version=='"'"'2.7'"'"'' 'numpy==1.13.3; python_version=='"'"'3.5'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"'' Check the logs for full command output.```
does whyever not work with Python 3.8, but with Python 3.7. But I got many warnings:
```
Collecting p5
  Using cached p5-0.6.0-py3-none-any.whl (100 kB)
Collecting triangle
  Using cached triangle-20190115.3.tar.gz (1.6 MB)
Collecting Pillow
  Downloading Pillow-7.0.0-cp37-cp37m-win_amd64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 2.2 MB/s
Collecting glfw
  Using cached glfw-1.10.1-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-win_amd64.whl (492 kB)
Collecting vispy
  Downloading vispy-0.6.4-cp37-cp37m-win_amd64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 3.3 MB/s
Collecting numpy
  Downloading numpy-1.18.1-cp37-cp37m-win_amd64.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 3.3 MB/s
Collecting freetype-py
  Downloading freetype_py-2.1.0.post1-py2.py3-none-win_amd64.whl (666 kB)
     |████████████████████████████████| 666 kB 177 kB/s
Installing collected packages: numpy, triangle, Pillow, glfw, freetype-py, vispy, p5
  WARNING: The script f2py.exe is installed in 'C:\Users\Laptop\AppData\Local\Programs\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    Running setup.py install for triangle ... \    WARNING: Subprocess output does not appear to be encoded as cp1252
|    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
    WARNING: Subprocess output does not appear to be encoded as cp1252
done
Successfully installed Pillow-7.0.0 freetype-py-2.1.0.post1 glfw-1.10.1 numpy-1.18.1 p5-0.6.0 triangle-20190115.3 vispy-0.6.4
```

**Comment by nakul-shahdadpuri** [comment]
Hi @Lightosk,
Popen in Windows wants shell commands encoded as cp1252. But this was fixed in python 3.X through the subprocess module.
try running 
```py
python -c "import sys; print(sys.stdout.encoding)"
```
and check the encoding. :)

**Comment by Lightosk** [comment]
I apologise for responding so late. I completely forgot about this, and it is such a long time ago, in the meanwhile I switched over to Linux and deleted Windows completely, so this is getting irrelevant. 
Sorry for the long time this issue was open for no reason.
