### ISSUE TITLE
Release notes for 0.5.0, release for 0.6.0?

### ISSUE THREAD

**Issue by jeremydouglass** [p5py/p5#151]
The last release is 0.5.0 (Aug 13, 2018) but it has no release notes.

There have also been 140+ commits to master since then. Would it be possible to just post some or all of them as a 0.6.0 release to bring the releases more up to date?

**Comment by abhikpal** [comment]
I think there's a numbering error somewhere (in the docs). Version 0.6.0 was released after the GSOC 2019. The release notes are [here](https://p5.readthedocs.io/en/latest/releasenotes/0.6.0.html). An installation using `pip` also installs version 0.6.0.

**Comment by jeremydouglass** [comment]
Hi @abhikpal -- I think I see the confusion. I can see that through pip and on https://pypi.org/project/p5/ 

What do you see when you click on the releases tab for this repo?

https://github.com/p5py/p5/releases

**Comment by parsoyaarihant** [comment]
v0.6.0 is released on Github: https://github.com/p5py/p5/releases/tag/v0.6.0

**Comment by jeremydouglass** [comment]
Thank you!

One additional change -- the release note first line says "Google Summer of Code 2020" -- it should be 2019.

**Comment by jeremydouglass** [comment]
Also:

https://pypi.org/project/p5/
has a broken image link to 
https://github.com/p5py/p5/blob/develop/docs/_static/readme.gif

I believe (?) that should be the "raw" URL:

https://github.com/p5py/p5/raw/develop/docs/_static/readme.gif
