### ISSUE TITLE
Occlusion of shapes in 3D Mode

### ISSUE THREAD

**Issue by parsoyaarihant** [p5py/p5#152]
In P3D mode, the shapes are not occluded according to their depth in the scene. 

For example, wen rendering the cone:
**To Reproduce**
```python
from p5 import *

def setup():
	size(640, 360)
	background(204)

def draw():
	background(205, 102, 94)
	rotate_x(frame_count * 0.01)
	rotate_y(frame_count * 0.01)
	cone(40, 70)

run(mode="P3D")
```

All the triangles of the geometry are seen. the triangles closer to the camera are not occluding the triangles farther from the camera.

![Screenshot 2020-04-07 at 12 57 50 PM](https://user-images.githubusercontent.com/15258498/78641822-67027880-78cf-11ea-88bd-47076489e060.png)

**Comment by tushar5526** [comment]
Are we drawing triangles on both the sides of a face(one on the side which is facing the user one on the side which is not facing the user ) ? Or only the outer triangle (the one which is facing the user)

**Comment by parsoyaarihant** [comment]
@tushar5526 , once the cone is tessellated into smaller triangles (https://github.com/p5py/p5/blob/master/p5/core/primitives3d.py#L348), all the triangles are sent to OpenGL for rendering (https://github.com/p5py/p5/blob/master/p5/sketch/renderer3d.py#L200). The problem is that, OpenGL is unable to use the depth of each triangle in the scene while rendering them correctly. Checkout Z-buffering: https://en.wikipedia.org/wiki/Z-buffering

**Comment by ziyaointl** [comment]
I managed to make some progress on this by explictly initializing the depth buffer.
However, z-fighting seems pretty bad. May need to make some modifications on how the lines are drawn.

![Screenshot from 2020-06-02 00-43-24](https://user-images.githubusercontent.com/18119047/83493964-6ff46e00-a46a-11ea-8481-50bc0a9865cc.png)

**Comment by ziyaointl** [comment]
After poking around some more, I realized that the default `depth_func` is `'less'`. Since the lines are always drawn after the triangles, changing the `depth_func` to `'lequal'` alleviates z-fighting quite a bit. There is still some left though... I shall look into transforming the lines towards the camera for an epsilon amount and check if that looks better.

![Screenshot from 2020-06-03 22-47-40](https://user-images.githubusercontent.com/18119047/83719861-d86b5880-a5ec-11ea-8fc6-6a25b520546c.png)

**Comment by ziyaointl** [comment]
Here are the results of transforming all line objects towards the camera before rendering:

Transformation used:
```python
inv(self.lookat_matrix).dot(translation_matrix(0, 0, Z_EPISLON).dot(self.lookat_matrix))
```

* `Z_EPISLON = 0` (i.e. do nothing)
![0](https://user-images.githubusercontent.com/18119047/83727225-95fc4880-a5f9-11ea-8be6-3027d9b85cbe.png)

* `Z_EPISLON = 0.5`
![0 5](https://user-images.githubusercontent.com/18119047/83727234-9ac0fc80-a5f9-11ea-86e6-2a76ea82e032.png)

* `Z_EPISLON = 1.0`
![1](https://user-images.githubusercontent.com/18119047/83727244-a01e4700-a5f9-11ea-9d2c-362c196e1600.png)

* `Z_EPISLON = 1.5`
![1 5](https://user-images.githubusercontent.com/18119047/83727262-a7455500-a5f9-11ea-9b28-5d228aedea75.png)

* `Z_EPISLON = 2.0`
![2](https://user-images.githubusercontent.com/18119047/83727288-add3cc80-a5f9-11ea-9e1a-b4ef5bce85ef.png)

* `Z_EPISLON = 100`
![100](https://user-images.githubusercontent.com/18119047/83727368-c9d76e00-a5f9-11ea-8b54-201b1e6ce1da.png)

`Z_EPISLON = 2.0` looks best to me using the default camera. I'll open a PR with this set to 2.
