### ISSUE TITLE
Output canvas to video or sequence of png's

### ISSUE THREAD

**Issue by ReneTC** [p5py/p5#155]
Not sure if it's possible, but I can't find anything online or in the documentation:
I think a useful feature would be to output the canvas to either video or a sequence of png's (maybe with alpha channel).

**Comment by jeremydouglass** [comment]
I believe that `saveFrame()` isn't implemented yet -- that it was prototyped in #31 #33 but never reimplemented in vispy.

**Comment by parsoyaarihant** [comment]
@ReneTC I have implemented `save_frames`, does this resolve this issue?

**Comment by ReneTC** [comment]
Thank you very much! Do you mind given an example how to use it? I'm new to this package. I tried saving this from the example page:
`from p5 import *

x = 0
y = 0
dim = 80.0

def setup():
        size(640, 360)
        no_stroke()

def draw():
        background(102)

        global x
        x = x + 0.8

        if x > width + dim:
                x = -dim

        translate(x, height/2 - dim/2)
        fill(255)
        rect((-dim/2, -dim/2), dim, dim)

        # Transforms accumulate. Notice how this rect moves
        # twice as fast as the other, but it has the same
        # parameter for the x-axis value
        translate(x, dim)
        fill(0)
        rect((-dim/2, -dim/2), dim, dim)

if __name__ == '__main__':
  run()
  
`

**Comment by parsoyaarihant** [comment]
Use this code: 

```python
from p5 import *

x = 0
y = 0
dim = 80.0

def setup():
    size(640, 360)
    no_stroke()

def draw():
    background(102)

    global x
    x = x + 0.8

    if x > width + dim:
            x = -dim

    translate(x, height/2 - dim/2)
    fill(255)
    rect((-dim/2, -dim/2), dim, dim)

    # Transforms accumulate. Notice how this rect moves
    # twice as fast as the other, but it has the same
    # parameter for the x-axis value
    translate(x, dim)
    fill(0)
    rect((-dim/2, -dim/2), dim, dim)

def mouse_pressed():
	save_frame("export.png")

if __name__ == '__main__':
  run()
```

when the mouse is pressed, the `save_frame()` function exports a png file. If you want to save a file for every frame, put the `save_frame` function inside `setup()`

**Comment by ReneTC** [comment]
Thank you for taking the time to help me out. I really appreicate that. Perfect!

**Comment by jeremydouglass** [comment]
@ReneTC -- great -- can this be closed, then?

**Comment by ReneTC** [comment]
@jeremydouglass
