### ISSUE TITLE
Mouse_x and mouse_y returning negative values

### ISSUE THREAD

**Issue by AJnsm** [p5py/p5#16]
**Test script:**

```python
from p5 import *
def setup():
    size(640, 360)
    background(255)

def draw():
    print(mouse_x, mouse_y)

run()
```
**Expected behavior:**
mouse_x and mouse_y respectively return values in the intervals [0, width] and [0, height]

**Actual behavior**
When quickly moving mouse outside of the output screen, negative values, and values exceeding width and height, get returned by mouse_x and mouse_y.

**p5 version:**
p5-0.3.0a2
**Python version:**
3.6.3
**Operating System:**
Mac OS 10.11.6 (El Capitan)

**Comment by abhikpal** [comment]
Yep! I can reproduce this on my machine as well. The should be trivial. I'll see if I can push a fix soon.
