### ISSUE TITLE
Cant use stroke_weight for points

### ISSUE THREAD

**Issue by portalgamesmais** [p5py/p5#161]
in processing.py you can use strokeWeight to change the size of points but in p5py points seems to always be 1 pixel regardless of using stroke_weight or not.

**Comment by jeremydouglass** [comment]
Thanks @portalgamesmais. Could you provide a simple example test sketch?

**Comment by portalgamesmais** [comment]
in processing.py the following sketch:
```python
def setup():
    size(200,200)
    noLoop()

def draw():
    background(0)
    stroke(255)
    point(10,50)
    strokeWeight(10)
    point(50,50)
```
results in:
![image](https://user-images.githubusercontent.com/20020373/80660637-aa7d7c00-8a62-11ea-85e6-1055ec0312a0.png)

wile in p5py the following sketch:
```python
from p5 import *


def setup():
    size(200,200)
    no_loop()

def draw():
    background(0)
    stroke(255)
    point(10,50)
    stroke_weight(10)
    point(50,50)

if __name__ == '__main__':
    run()

```
results in:
![image](https://user-images.githubusercontent.com/20020373/80660784-1233c700-8a63-11ea-92a2-88930aed5103.png)

**Comment by tushar5526** [comment]
I can't reproduce the issue on pycharm using the project from github, but can reproduce when it when I am using the package installed by pip

Running on pycharm
![Screenshot from 2020-04-30 18-01-45](https://user-images.githubusercontent.com/30565750/80711122-7a3ee780-8b0d-11ea-8024-02f56acf7964.png)

Running using terminal
![Screenshot from 2020-04-30 18-02-55](https://user-images.githubusercontent.com/30565750/80711129-7d39d800-8b0d-11ea-9e8f-21f69f00a89f.png)

Can someone confirm this or am I doing something wrong ?

**Comment by DamasdiGabor** [comment]
I also have this problem. I have installed p5 using pip. Since this was my first try with p5 it took me a while to convince myself that this is a bug.

**Comment by jeremydouglass** [comment]
For anyone thinking about working on this issue: The way that points are rendered in Processing(Java) is surprisingly complex under the hood due to support for strokeCap and how the behavior aligns with PostScript / CSS. So, in addition to stroke() making points bigger, strokeCap may make points invisible.

For recent discussion in Processing / Processing-docs, see:

https://github.com/processing/processing-docs/issues/792
https://github.com/processing/processing/issues/5957
