### ISSUE TITLE
Wrong error code? <bound method Sketch.on_timer of Sketch> when passing scalar instad of tuple

### ISSUE THREAD

**Issue by ReneTC** [p5py/p5#166]
**Describe the bug**
If I call the a shape function, but forgets the cordinates should be a tuple:
`circle(0,0,100)`

I get the error 
` <bound method Sketch.on_timer of Sketch>`

**Expected behavior**
I think we should add an assert saying something like
"first argument should be a tuple"
It's confusing coming from p5js, and the error code is nonsense.

I'm new to contributing. I would love to hear if this is a bad idea for python packages.

**Comment by jeremydouglass** [comment]
Why was this closed -- is it resolved in some recent commit?

**Comment by ReneTC** [comment]
no feedback so I felt I just added unneccery noise
