### ISSUE TITLE
Tutorial wrong? pop_matrix() does nothing, but should be refered as reset_matrix() instead

### ISSUE THREAD

**Issue by ReneTC** [p5py/p5#180]
**Describe the bug**
The [tutorial on readthedocs ](https://p5.readthedocs.io/en/latest/tutorials/2D%20transformations.html)describes how pop_matrix() resets the coordinate system. 

**To Reproduce**
The following  should set a circle at position 100*100, since the translation should not do anything  doesn't do anything between push and pop. (green circle in the image)
```
push_matrix()
translate(100,100)
pop_matrix()
circle((100,100),50)
```

However, a circle appears at position (200,200) not (100,100)

**Expected behavior**
I would expect pop_matrix() to call an error since it does not exist? seems that nothing happens. The correct way to do it is calling reset_matrix(). It does exactly what the tutorial describes.  (yellow circle in the image)

```
push_matrix()
translate(100,100)
reset_matrix()
circle((100,100),50)
```
We should rename reset_matrix() to pop_matrix.
Or rename push_matrix() to save_matrix() or something. 

I'm new to p5py but tried p5.js a little bit. This confused me a lot. 

**Screenshots**
Green colour is circle with pop_matrix() - it does nothing.
Yellow colour is circle with reset_matrix(). Expected behavour with pop_matrix() 
![image](https://user-images.githubusercontent.com/40211569/83978130-a831fb80-a905-11ea-96c8-e268d3b6ab65.png)

**Comment by ReneTC** [comment]
I'm not sure if reset_matrix() just resets everything no matter what. But there is not mention of the pop_matrix() on [readthedocs](https://p5.readthedocs.io/en/latest/reference/transform.html?highlight=reset_matrix()#reset-matrix)

**Comment by parsoyaarihant** [comment]
@ReneTC , please use 

```
with push_matrix():
        ....Some Code.....
```

We are currently working on supporting both the syntaxes. 

#156

**Comment by ReneTC** [comment]
Thank you @parsoyaarihant . I see it's a duplicate of #156.
