### ISSUE TITLE
begin_shape('POINTS') does not draw points

### ISSUE THREAD

**Issue by ziyaointl** [p5py/p5#186]
**Describe the bug**
begin_shape('POINTS') does not draw points

**To Reproduce**
```python
from p5 import *

def draw():
        begin_shape('POINTS')
        vertex(30, 20)
        vertex(85, 20)
        vertex(85, 75)
        vertex(30, 75)
        end_shape()

if __name__ == '__main__':
        run()
```

**Expected behavior**
For points appear on the screen.

**Screenshots**
Expected (from Processing Language):
<img width="240" alt="Screen Shot 2020-06-20 at 9 32 05 AM" src="https://user-images.githubusercontent.com/18119047/85206802-51e79400-b2d9-11ea-8eba-e0b5542a072d.png">

Actual:
![Screen Shot 2020-06-20 at 9 32 24 AM](https://user-images.githubusercontent.com/18119047/85206804-58760b80-b2d9-11ea-8983-6dc3f8b22953.png)

**System information:**
 - p5 release (version number or latest commit): 975f07e75a48aa7ebc8225a9cb5b27fda8795bb8
 - Python version: 3.8.3
 - Operating system: MacOS 10.15.5

**Comment by ziyaointl** [comment]
Maybe we can use `p5.circle` instead of the OpenGL primitive `points`. This way we can easily replicate the behavior here: https://p5js.org/reference/#/p5/point

**Comment by parsoyaarihant** [comment]
Yes, we would also solve #161

**Comment by jeremydouglass** [comment]
Yes, for the vispy / OpenGL renderer I recommend looking closely at how Processing(Java) (not p5.js) implements point(), and what strokeWeight / strokeCap do to a point.
