### ISSUE TITLE
Inconsistent behavior for Arc

### ISSUE THREAD

**Issue by ziyaointl** [p5py/p5#188]
**Describe the bug**
The behavior for Arc in p5py does match with the Processing Language

**To Reproduce**
```python
from p5 import *

def draw():
    offset = 0
    x = 0
    while x < 2 * PI:
        arc((50.0 + offset, 50.0), 50.0, 50.0, x, 2 * PI)
        arc((50.0 + offset, 100), 50, 50, x, 2 * PI, 'OPEN')
        arc((50.0 + offset, 150), 50, 50, x, 2 * PI, 'CHORD')
        arc((50.0 + offset, 200), 50, 50, x, 2 * PI, 'PIE')
        x += QUARTER_PI
        offset += 50

if __name__ == '__main__':
    run()
```

```java
void setup() {
  size(640, 360);
}

void draw() {
  int offset = 0;
  for (float x = 0; x < PI * 2; x += QUARTER_PI) {
     arc(50.0 + offset, 50.0, 50.0, 50.0, x, 2*PI);
     arc(50.0 + offset, 100, 50, 50, x, 2*PI, OPEN);
     arc(50.0 + offset, 150, 50, 50, x, 2*PI, CHORD);
     arc(50.0 + offset, 200, 50, 50, x, 2*PI, PIE);
     offset += 50;
  }
}
```

**Expected behavior**
<img width="752" alt="Screen Shot 2020-06-22 at 11 47 09 PM" src="https://user-images.githubusercontent.com/18119047/85369950-dbb67d80-b4e2-11ea-9e57-18bec7b75dc5.png">

**Actual Behavior**
<img width="626" alt="Screen Shot 2020-06-22 at 11 47 25 PM" src="https://user-images.githubusercontent.com/18119047/85369939-d6f1c980-b4e2-11ea-84c8-623d7c0dfc64.png">

**System information:**
 - p5 release (version number or latest commit): 975f07e75a48aa7ebc8225a9cb5b27fda8795bb8
 - Python version: 3.8.3
 - Operating system: MacOS 10.15.5

**Comment by ziyaointl** [comment]
Some progress on the tessellation branch:
<img width="629" alt="Screen Shot 2020-06-26 at 2 24 24 AM" src="https://user-images.githubusercontent.com/18119047/85842211-30acfa80-b754-11ea-9eb7-e08ae663fc87.png">

**Comment by jeremydouglass** [comment]
@ziyaointl -- congratulations on this great work.

Could you comment on the remaining difference between the "expected" image above and the latest pipeline? It seems like there is a column of points and a line on the right edge that is missing. If that is the case, should those remaining differences in behavior be noted in an open issue -- even if they are not a high priority?

**Comment by ziyaointl** [comment]
@jeremydouglass Thanks! I think the column of points is actually a bug in Processing. The last column has start angle and end angle both set at 2*PI. Therefore, I think it's sensible for the behavior to be "not draw anything" but it could also be undefined. In p5.js, only PIE mode shows a small dot, and all other rows are empty.

<img width="419" alt="Screen Shot 2020-06-30 at 6 34 16 PM" src="https://user-images.githubusercontent.com/18119047/86193446-c8b63580-bb00-11ea-865d-a0c1dcab97ed.png">

**Comment by jeremydouglass** [comment]
Interesting! So would you suggest bug reports on the Processing repo / the p5.js repo?

It is an edge case, but nice if we can collectively minimize "undefined" as much as possible in visual outputs. arc() is already frustrating enough without also being inconsistent...

**Comment by ziyaointl** [comment]
Yeah, that's a good idea. I opened the respective issues here:
https://github.com/processing/processing/issues/6063
https://github.com/processing/p5.js/issues/4664
