### ISSUE TITLE
Simulation how a laser works [Created something cool with p5]

### ISSUE THREAD

**Issue by ReneTC** [p5py/p5#193]
Not sure if this fits here, but the contribution file said I should post if I used p5py for something cool - so here goes.
I made an article showing the relevant atom-light interaction and  a working laser simulation all via p5py.

[It's here](https://medium.com/@Higgsino/the-surprisingly-simple-physics-of-a-laser-47d7d23e928e)

In a few days I'll convert the article for a video on my[ channel](https://www.youtube.com/channel/UC02-e6K7o5_bPw0weXh3W3g). I'll be sure to spread to word about p5py.

Thank you very much for helping me. specificly for implementing the save-frame function :)

**Comment by parsoyaarihant** [comment]
@ReneTC , thank you for sharing this. Projects like this keeps us motivated to keep work on p5py.

You could also share this post on Processing discourse: https://discourse.processing.org/c/gallery/21

**Comment by ReneTC** [comment]
Thank you @parsoyaarihant good idea. I'm very excited about your recent impressive skia test.

**Comment by parsoyaarihant** [comment]
@ReneTC , I am still thinking if skia should be integrated into p5py or a separate library be built. The current implementation of p5py is built using only a single renderer. Hence, the code is customised to that particular renderer. To support multiple renderers, the library needs to be restructured before a new renderer can be added.

**Comment by parsoyaarihant** [comment]
#212

**Comment by parsoyaarihant** [comment]
We now have a separate category on Discourse: https://discourse.processing.org/c/p5py/27
This would be a great platform to share your work and get feedback from entire community. 

Thanks.
