### ISSUE TITLE
remap map to remap

### ISSUE THREAD

**Issue by Haksell** [p5py/p5#201]
**Describe the bug**
Not sure if it fits here but I have a "bug" report in this section of the documentation: https://p5.readthedocs.io/en/latest/guides/for-processing-users.html#math

**Screenshots**
<img width="705" alt="remap" src="https://user-images.githubusercontent.com/33573717/88072023-d6e1f980-cb74-11ea-894f-82174bf9daf8.png">
The bottom line should use `remap`, not `map`.

**Comment by Andy-Python-Programmer** [comment]
Hi I have made a pull request for this issue just ignore the #218 pull request.
