### ISSUE TITLE
Good First Issues ?

### ISSUE THREAD

**Issue by Andy-Python-Programmer** [p5py/p5#208]
It’s a question rather than an issue that are there some good first issues for new contributors I will love to contribute.

**Comment by Andy-Python-Programmer** [comment]
I have added a troubleshooting section in the documentation. It would be nice to have issues tagged with good first issue 👍

**Comment by Andy-Python-Programmer** [comment]
#207

**Comment by Andy-Python-Programmer** [comment]
#207

**Comment by parsoyaarihant** [comment]
#212
