### ISSUE TITLE
Basic execution error works in IDLE not in .py file

### ISSUE THREAD

**Issue by jaydenrre** [p5py/p5#21]
**Test script:**

```python
# put your test script here
from p5 import *
size(500,500)
run()

```

**Expected behavior:**
run a 500 x 500 window

**Actual behavior**
error

**Errors produced (if any):**
Traceback (most recent call last):
  File "C:\Users\jayden\Desktop\p5.py", line 1, in <module>
    from p5 import *
  File "C:\Users\jayden\Desktop\p5.py", line 2, in <module>
    size(500,500)
NameError: name 'size' is not defined

[idle works fine](https://i.imgur.com/2K78wUy.jpg)

[the script returns an error](https://i.imgur.com/3XJMloO.jpg)

**p5 version:**
p5 (0.3.0a2)

**Python version:**
3.5
**Operating System:** 
windows

**Comment by abhikpal** [comment]
Hmm.. interesting. Seems to work perfect fine for me:

![iss-21 seems to be working fine...](https://i.imgur.com/xgzCESP.gif?raw=true)

I see that you have named your file ```p5.py```, could that be the issue?

**Comment by jaydenrre** [comment]
hahaha   didn't even consider that. that was exactly the problem.  

my bad.

thanks!

**Comment by jaydenrre** [comment]
Yeah naming it p5 breaks it.
My bad ha ha didn't think of it.

Thanks!
