### ISSUE TITLE
Tic Tac Toe Human [Made  Something Cool With P5]

### ISSUE THREAD

**Issue by Andy-Python-Programmer** [p5py/p5#211]
Hello everyone I made something kinda cool with p5.py. This is my first project with p5.py and maybe the best gui I have ever made in python as all most all the time I do stuff that has backed. I love this library 👍    

![d](https://user-images.githubusercontent.com/62820092/89095743-239abf80-d414-11ea-9866-d063bf7a4d8e.png)

Thank You :)

**Comment by parsoyaarihant** [comment]
We now have a separate category on Discourse: https://discourse.processing.org/c/p5py/27
This would be a great platform to share your work and get feedback from entire community. 

Thanks.
