### ISSUE TITLE
Add support for renderer attribute in run() function

### ISSUE THREAD

**Issue by parsoyaarihant** [p5py/p5#213]
Add new attribute called `renderer` in `run()` function. The attribute should initiate the renderer based on the value passed. 

For example to use vispy: `run(renderer="vispy")`

In future when new renderers are added, they can be initialised using this attribute.

**Comment by Andy-Python-Programmer** [comment]
I want to work on this issue but if I write the code or even try to run it I get this error:
```python
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\p5\\sketch\\shaders\\2d\\default2d.vert'```

**Comment by parsoyaarihant** [comment]
Can you open a new issue for this? With the code you are trying to run

**Comment by Andy-Python-Programmer** [comment]
I have just forked and downloaded this repo to work on this issue. No changes are made
