### ISSUE TITLE
Update Public APIs to support different renderers

### ISSUE THREAD

**Issue by parsoyaarihant** [p5py/p5#214]
Currently all the APIs use PShape only for rendering shapes as vispy is the only renderer being used. To add support for new renderers, we want to update the existing API functions to call that specific renderer. Pseudo code:

``` python
def shapeXYZ(): # some rendering function
    renderer.shapeXYZ() # the function corresponding to the renderer will be called.
```

**Comment by parsoyaarihant** [comment]
Few more things needs to be done after #288 

1. Implement begin_shape() API inside the Vispy2DRenderer

**Comment by parsoyaarihant** [comment]
2. Test if the Font and Image APIs are working as expected with the new library structure.

**Comment by tushar5526** [comment]
It skipped my mind to refactor `image.py` as it has a dependency on **Texture2D** from `vispy.gloo`. Image APIs are working fine as of now, as there is only one renderer. 
`PImage` has to be updated to support multiple renderers. I will make a PR soon.

**Comment by parsoyaarihant** [comment]
#289

**Comment by tushar5526** [comment]
> Few more things needs to be done after #288
> 
> 1. Implement begin_shape() API inside the Vispy2DRenderer

@parsoyaarihant  Can you tell a bit more about this? I am interested in doing it.

**Comment by parsoyaarihant** [comment]
begin_shape() API currently uses PShape: https://github.com/p5py/p5/blob/master/p5/core/vertex.py#L335

We need to move this code into the VispyRenderer.
