### ISSUE TITLE
Update installation scripts

### ISSUE THREAD

**Issue by ziyaointl** [p5py/p5#222]
After the removal of `triangle` and the introduction of `PyOpenGL`, the `setup.py` file is now out-of-date. Fix that.

**Comment by Andy-Python-Programmer** [comment]
Can I try to work on this issue!!!

**Comment by ziyaointl** [comment]
@Andy-Python-Programmer Sure! I can unassign myself. Let me know if you have any questions!

**Comment by Andy-Python-Programmer** [comment]
Hi @ziyaointl I have made a pull request. That may fix the issue!!!
