### ISSUE TITLE
Key.text returns its char code, not its str value; causes crashes when using its __str__ method

### ISSUE THREAD

**Issue by Nathansbud** [p5py/p5#229]
At least for key_released(), attempting to print(event.key) fails, as the \_\_str__ method being called is trying to call isalnum:

```
class Key:
   #omitted code
    def __str__(self):
        if self.text.isalnum():
            return self.text
        else:
            return self.name
```

However, text holds the char code—an int—which causes a crash. This may only be true in key_released; I'm currently getting around it by accessing text/name directly, but it's a rather annoying crash.

**Comment by Andy-Python-Programmer** [comment]
https://github.com/p5py/p5/blob/7d030882df846efb34989ca2bb2ce3b6d1011aa9/p5/sketch/events.py#L103

**Comment by Nathansbud** [comment]
@Andy-Python-Programmer Yep, that's what I'm referencing—the isalnum call raises an error, as Key.text (at least when referenced from key_released) is an int, not a string.

**Comment by tushar5526** [comment]
Hey @Nathansbud can you provide the test code too, print(event.key) is working fine for me.
Also specify which version of p5 are you using.

**Comment by Andy-Python-Programmer** [comment]
Hi @Nathansbud maybe do `pip install -U git+ https://github.com/p5py/p5 `

**Comment by Nathansbud** [comment]
Hey y'all, my bad—I think I was using an old version. Installing the most recent fixed it @Andy-Python-Programmer, thank you! Sorry for the confusion.

**Comment by Andy-Python-Programmer** [comment]
No problem 👍🏼
