### ISSUE TITLE
no offline versions for the documentation!!

### ISSUE THREAD

**Issue by tusqasi** [p5py/p5#239]
I made some offline versions, zipped HTML, and pdf.
here is my [fork](github.com/tusqasi/p5).
Someone (like me) might want an offline version so made one for them.
post this somewhere.

Sorry if this is the wrong place for this.

**Comment by abhikpal** [comment]
The documentation system (readthedocs) automatically generates a PDF which can be accessed by clicking on the version indicator at the bottom of the sidebar (it might say "v:latest" for instance). Here is the PDF for the latest version: https://p5.readthedocs.io/_/downloads/en/latest/pdf/ 

However rendering issues do exist in the automatically generated PDF, so the correct way to fix it is to tweak the sphinx settings.

I'm closing this for now.

**Comment by tusqasi** [comment]
Oh. My bad. That `v:latest` is way out of sight. I couldn't find it.
Thanks
