### ISSUE TITLE
Add Data Storage module 

### ISSUE THREAD

**Issue by tushar5526** [p5py/p5#258]
**Is your feature request related to a problem? Please describe.**
Add a Data Storage Module in p5py, in accordance with p5.js

**Describe the solution you'd like**
Add data storage for p5py that is platform independent with the same functionalities as p5.js.

I would be glad to work on this.

**Comment by tushar5526** [comment]
Closing

**Comment by parsoyaarihant** [comment]
Tip: In your PR commits, if you mention "Fixed #123" it will automatically close the issue once the PR gets merged.
