### ISSUE TITLE
Import dataclasses error

### ISSUE THREAD

**Issue by tushar5526** [p5py/p5#262]
```
Traceback (most recent call last):
  File "/home/tushar55/p5/try.py", line 1, in <module>
    from p5 import *
  File "/home/tushar55/p5/p5/__init__.py", line 19, in <module>
    from .sketch import *
  File "/home/tushar55/p5/p5/sketch/__init__.py", line 21, in <module>
    from .userspace import *
  File "/home/tushar55/p5/p5/sketch/userspace.py", line 37, in <module>
    from .renderer2d import Renderer2D
  File "/home/tushar55/p5/p5/sketch/renderer2d.py", line 34, in <module>
    from .openglrenderer import OpenGLRenderer, get_render_primitives, COLOR_WHITE
  File "/home/tushar55/p5/p5/sketch/openglrenderer.py", line 8, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by tushar5526** [comment]
@ziyaointl

**Comment by parsoyaarihant** [comment]
Which python version are you using?

**Comment by ziyaointl** [comment]
Adding onto what @parsoyaarihant asked, dataclasses exist as a backport in 3.6 and were officially added in 3.7 and beyond.

**Comment by parsoyaarihant** [comment]
If it needs to be installed separately for 3.6, we can add it into the requirements folder.

**Comment by tushar5526** [comment]
@parsoyaarihant  3.6.9

**Comment by ziyaointl** [comment]
Before releasing the version that required dataclasses I tried pip installing p5 in a fresh virtual environment and it worked back then, since it is part of setup.py here: https://github.com/p5py/p5/blob/31c005c52a4adbea8a4a89bfd4a57b0334e8eb46/setup.py#L14

@tushar5526 What command(s) did you run to install the latest version of p5?

**Comment by tushar5526** [comment]
Didn't ran setup.py, just cloned it, installed the requirements, and started working on it.

**Comment by ziyaointl** [comment]
I see. I'll look into adding this dependency to requirements.py.
