### ISSUE TITLE
from p5 import * results in "ImportError: cannot import name 'AbstractContextManager'"

### ISSUE THREAD

**Issue by katesfb** [p5py/p5#272]
**Describe the bug**
When trying to import P5 into a python 'sketch' results in the error "ImportError: cannot import name 'AbstractContextManager' "

**To Reproduce**
SImply type "from p5 import * "

**Expected behavior**
I expect the above import of p5 library to work with no import errors

**System information:**
 - p5 release (0.7.1):
 - Python version: 3.5.2
 - Operating system: LInux mint 18.2 (Sonya)

**Additional context**
```
from p5 import *
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    from p5 import *
  File "/home/richard/.local/lib/python3.5/site-packages/p5/__init__.py", line 19, in <module>
    from .sketch import *
  File "/home/richard/.local/lib/python3.5/site-packages/p5/sketch/__init__.py", line 21, in <module>
    from .userspace import *
  File "/home/richard/.local/lib/python3.5/site-packages/p5/sketch/userspace.py", line 30, in <module>
    from .base import Sketch
  File "/home/richard/.local/lib/python3.5/site-packages/p5/sketch/base.py", line 26, in <module>
    from ..core import p5
  File "/home/richard/.local/lib/python3.5/site-packages/p5/core/__init__.py", line 18, in <module>
    from .structure import *
  File "/home/richard/.local/lib/python3.5/site-packages/p5/core/structure.py", line 18, in <module>
    from contextlib import AbstractContextManager
ImportError: cannot import name 'AbstractContextManager'

```

**Comment by jeremydouglass** [comment]
AbstractContextManager is Python 3.6+.

https://docs.python.org/3.6/library/contextlib.html
https://docs.python.org/3.5/library/contextlib.html

It looks like you are running it with 3.5 -- that would cause the import statement in /core/structure.py to fail.

**Comment by ziyaointl** [comment]
@katesfb Were you able to try using p5 with a newer Python version?

**Comment by ziyaointl** [comment]
Closing this for now due to inactivity

**Comment by jeremydouglass** [comment]
@ziyaointl -- I think this raises a documentation error. p5 clearly fails on Python < 3.6, but the docs say:

> p5 requires Python 3. Most recent versions of MacOS and Linux systems should have an installation of Python already. If you’re not sure which version your computer is using, run
> 
>     python --version
> 
> from a terminal window. If the reported version is greater than 3.0, you’re good to proceed.

...so, that's wrong. Should open a separate issue, or re-open this and close it out here?

**Comment by ziyaointl** [comment]
@jeremydouglass Thanks for pointing this out! I think reopening this issue is ok since this should be a quick fix.
