### ISSUE TITLE
[Discussion] Supporting Both p5py and Processing APIs

### ISSUE THREAD

**Issue by parsoyaarihant** [p5py/p5#280]
https://discourse.processing.org/t/api-compatibility-for-p5py/20492

Its possible for p5py to support both APIs of p5py and Processing by simply copying existing functions into new objects with different name: 

``` python
mousePressed = mouse_pressed
mouseX = mouse_X
...
```

My idea is to keep both the APIs in p5py. Over time, through online discussions and peoples feedback, we can settle on which one users prefer. 

Technically its quite simple task. And I believe it would make a lot of people happy.

**Comment by tushar5526** [comment]
Yes, this will be a better solution.

**Comment by abhikpal** [comment]
Since we eventually want to standardize the API with the other processing dialects, this seems like a reasonable change to me. 

> My idea is to keep both the APIs in p5py. Over time, through online discussions and peoples feedback, we can settle on which one users prefer.

Also a very good idea. It also doesn't seem too much work to continue supporting both versions of the API.

**Comment by jeremydouglass** [comment]
This is a great idea!

Many of the changes will be remapping underscores to internal caps (snake_case to camelCase), so I wouldn't anticipate collisions. However, it might make sense to have one set of mappings as an explicit import, and one as the default. A big selling point of p5py is that you can use it in your python environment of choice with your tooling of choice, and having only one version of the API loaded in at a time would make the namespace cleaner and the tooling cleaner to use -- e.g. code completion on IDEs et cetera.

**Comment by tushar5526** [comment]
I would like to work on this during hacktoberfest !
