### ISSUE TITLE
Close stale issues automatically [ Github Actions ]

### ISSUE THREAD

**Issue by tushar5526** [p5py/p5#283]
Found some GitHub actions to add this feature.
Is it required as of now as there are many stale issues out there?

**Comment by jeremydouglass** [comment]
Honestly, with a project like this (~50 open issues, mostly developer-created) I personally don't think it is a good idea to auto-close anything. Better to just do sprints and close stale issues manually -- or leave them open and just take them as someday if they aren't milestoned.

Closing "stale" issues works best for projects with big users bases, *lots* of issues that are often non-developer created requests, and especially when the code is evolving rapidly and old requests are probably no longer relevant or should be made again if they are important -- hence "stale". That doesn't seem like a good fit for this project right now IMO.

**Comment by tushar5526** [comment]
Closing this, thank you @jeremydouglass for the reponse
