### ISSUE TITLE
Shape class cannot take standard tuples for vertices

### ISSUE THREAD

**Issue by lajaybird** [p5py/p5#30]
The documentation of the class `Shape()` suggests that vertices should be passed as 3-tuples, yet tessellation requires each element in `_raw_vertices` to have the property `flag`.

**p5 version:** e78c4a8

**Comment by abhikpal** [comment]
That is correct. The doc string of the Shape class was a bit misleading. Right now we are only using the shape class internally (it's not part of the public API, yet), and passing it named tuples. 

I've changed the doc string to reflect that.

Thanks for pointing this out!

**Comment by lajaybird** [comment]
Yeah, there seems to be a number of issues with its current implementation as `compute_faces` requires the shape to be at most a quadrilateral for it to operate correctly. I've been looking into triangulation algorithms in hopes of remedying this.
