### ISSUE TITLE
Implement saveFrame()

### ISSUE THREAD

**Issue by friedkeenan** [p5py/p5#31]
I tried to save a frame but saw that it wasn't in this library, so I looked up how to do it in pyglet:

    pyglet.image.get_buffer_manager().get_color_buffer().save(filename)

You could then make a save_frame(filename) function that maybe parses the string like processing does to replace the "###" with the right number, and then it runs that line of code.

It's not urgent or anything, but I think it'd be nice to have

**Comment by abhikpal** [comment]
Hey, sorry for getting back to this so late.

@innovationchef used your suggestion here to to implement this in #33, it's worth looking at @Manindra29 and my comment on the thread there if you're interested in implementing this.

**Comment by parsoyaarihant** [comment]
`saveFrame` is implemented in p5py: https://github.com/p5py/p5/commit/1885fda916dc493f8efa3b1cc0bdc58ebf894ce2
