### ISSUE TITLE
mouse_x and mouse_y are affected by translation.

### ISSUE THREAD

**Issue by lajaybird** [p5py/p5#32]
**Test script:**

```python
from p5 import *

def setup():
    size(1558, 1695)
    background(0)

def draw():
    background(0)
    translate(width/2, height/2)

    p1 = (-300, -300)
    p2 = (mouse_x, mouse_y)
    p3 = (300, -300)

    fill(255)
    triangle( p1, p2, p3 )

if __name__ == "__main__":
    run()
```

**Expected behavior:**
![expected](https://user-images.githubusercontent.com/11286340/34638749-d312687a-f297-11e7-88ad-58a1a3c12837.gif)

**Actual behavior**
![actual](https://user-images.githubusercontent.com/11286340/34638752-d8521e84-f297-11e7-9198-71a8a44ee210.gif)

**Errors produced (if any):** None

**p5 version:** e78c4a8

**Python version:** 3.6
**Operating System:** Arch Linux

**Comment by abhikpal** [comment]
This seems to be the behavior in Processing (JAVA) as well:
![iss32](https://user-images.githubusercontent.com/3626001/34640406-6010855e-f2f2-11e7-9793-7653541dbd62.gif)
