### ISSUE TITLE
When using pip install p5 get long error

### ISSUE THREAD

**Issue by rekkep** [p5py/p5#335]
Using Python3.10.1 with pip 21.3.1 on MacOs Monterey

Error:
[Full console message](https://github.com/p5py/p5/files/7872928/Error.code.txt) and the short error message (the first line is in white and the rest in red): 

> Running setup.py install for PyOpenGL-accelerate ... error
>     ERROR: Command errored out with exit status 1:
>      command: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c8/bss7qyk915n86xfgm4y2kp0h0000gn/T/pip-install-5rrhbzu5/pyopengl-accelerate_b63e711e5781408287c55a168acc91c5/setup.py'"'"'; __file__='"'"'/private/var/folders/c8/bss7qyk915n86xfgm4y2kp0h0000gn/T/pip-install-5rrhbzu5/pyopengl-accelerate_b63e711e5781408287c55a168acc91c5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/c8/bss7qyk915n86xfgm4y2kp0h0000gn/T/pip-record-ftjood3x/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/PyOpenGL-accelerate
>          cwd: /private/var/folders/c8/bss7qyk915n86xfgm4y2kp0h0000gn/T/pip-install-5rrhbzu5/pyopengl-accelerate_b63e711e5781408287c55a168acc91c5/

**Comment by ziyaointl** [comment]
Apologies for this late reponse. I found another case of PyOpenGL not working with python 3.10 [here](https://stackoverflow.com/questions/70403764/cant-install-pyopengl-accelerate-gcc-failed-with-exit-code-1). Could you try installing again using python 3.8?

**Comment by dancharrington** [comment]
Having the same issue with Python 3.8.2 using VSCode on OSX. I have installed GLFW and Vispy separately.

**Comment by FenrisAureus** [comment]
how did you fix it?

**Comment by ziyaointl** [comment]
#350 This PR might solve this issue, since PyOpenGL has been updated. You can get it via cloning the p5py repo directly from Github and running `pip install .` inside of the cloned folder.
