### ISSUE TITLE
Implement PImage, loadImage(), image()

### ISSUE THREAD

**Issue by the-visualizer** [p5py/p5#34]
I am trying to translate a Processing sketch of mine to Python, using p5py.
Here it is, albeit incomplete - https://github.com/the-visualizer/bike_roller 
I found the following to be missing:

- load_image()
- p_image declaration [for assigning variables with the loaded image]
- image()  

**p5 version:** 0.3.0a2

**Python version:** Pyhton 3.5.2
**Operating System:** Ubuntu 16.04 (64-bit)

**Comment by parsoyaarihant** [comment]
These functions have been implemented.
