### ISSUE TITLE
Deprecate python 3.6 support

### ISSUE THREAD

**Issue by ziyaointl** [p5py/p5#351]
Python 3.6 is currently EOL and receives no updates. As a consequence, many libaries (e.g. numpy, pillow) that we depend on also dropped 3.6 support in their newer versions. We should drop 3.6 support as well in the next release.

**Comment by tushar5526** [comment]
Yes, I was thinking of that as well. I am thinking of trying to migrate to 3.9 or 3.10.Also, it would be better to integrate typing module with p5py somewhere in future.

I will make a PR after merging the first skia draft.

**Comment by ziyaointl** [comment]
Thanks @tushar5526! I do think we should attempt to support as many current python versions as reasonable, so maybe we shouldn't raise the minimum requirement all the way to 3.9 or 3.10 yet, but we should make sure that we are compatible with those higher versions.

**Comment by tushar5526** [comment]
Agreed! So, we should move the min-requirements to 3.7 then and support the higher versions as well. I will update the GHAs and test soon for python>=3.7
