### ISSUE TITLE
New Release v0.8.0

### ISSUE THREAD

**Issue by tushar5526** [p5py/p5#360]
- [x] Increment the version number in setup.py
- [x] Create a new tag with that version
- [x] Write some update logs summarizing the updates since last update, include this in both the p5py docs and the github release note
- [x] Create a new release on Github
- [x] Create a new release on pypi

**Comment by tushar5526** [comment]
Hey @ziyaointl 

How are we generating the release assets in p5py. I see that in older assets we include the docs as well, whereas with the command `python -m build` docs are not included in the `wheels` or `tar ball`. 

Do we have to generate different builds for GitHub release and pypi release ?

**Comment by ziyaointl** [comment]
I think the assets in previous releases on Github were automatically generated by Github, which were just zipped/tarred source code at the specified tag. Hence the docs were left in. You could continue using the automatically generated assets, or you could also upload the assets generated by `python -m build`. Up to you :)

**Comment by tushar5526** [comment]
Closing this. We have a new release!
