### ISSUE TITLE
raise an error, when Vector.normalize() tries to normalize a "zero-vector"

### ISSUE THREAD

**Issue by Devrim-Celik** [p5py/p5#37]
**Test script:**
Problem is, when you try to normalize a Vector Object, which only has zero value, it tries to divide
them by 0 (their current magnitude), setting the values to ```nan```. It would be handy if a error would pop up.
```python
from p5 import *

x = Vector(0, 0)

print(x.magnitude)
x.normalize()
print(x)
print(x.magnitude)
```

**Expected behavior:**
```
0.0
ValueError(...)
```

**Actual behavior**
```
0.0
Vector(nan, nan, nan)
nan
```

**Errors produced (if any):**

**p5 version:**
0.3.0a2

**Python version:**
Python 3.6.4

**Operating System:** 
MacOS

**Comment by parsoyaarihant** [comment]
See #38 .
