### ISSUE TITLE
Feature: Typography support for Skia

### ISSUE THREAD

**Issue by tushar5526** [p5py/p5#371]
### Attributes

- [x] [textAlign()](https://p5js.org/reference/#/p5/textAlign)
- [x] [textLeading()](https://p5js.org/reference/#/p5/textLeading)
- [x] [textSize()](https://p5js.org/reference/#/p5/textSize)
- [x] [textStyle()](https://p5js.org/reference/#/p5/textStyle)
- [x] [textWidth()](https://p5js.org/reference/#/p5/textWidth)
- [x] [textAscent()](https://p5js.org/reference/#/p5/textAscent)
- [x] [textDescent()](https://p5js.org/reference/#/p5/textDescent)
- [x] [textWrap()](https://p5js.org/reference/#/p5/textWrap)

### Loading & Displaying

- [x] [loadFont()](https://p5js.org/reference/#/p5/loadFont)
- [x] [text()](https://p5js.org/reference/#/p5/text)
- [x] [textFont()](https://p5js.org/reference/#/p5/textFont)
- [ ] [p5.Font](https://p5js.org/reference/#/p5.Font)

**Comment by tushar5526** [comment]
Hey @ziyaointl, should we implement `preload` for p5py. [Preload docs link](https://p5js.org/reference/#/p5/preload)

> Called directly before [setup()](https://p5js.org/reference/#/p5/setup), the [preload()](https://p5js.org/reference/#/p5/preload) function is used to handle asynchronous loading of external files in a blocking way. If a preload function is defined, [setup()](https://p5js.org/reference/#/p5/setup) will wait until any load calls within have finished

It seems preload waits for the asynchronous functions to finish and then proceeds with `setup` and `draw`.

We can just load stuff before the `setup` in our python sketches so it seems there is no specific need for a preload function IMO.

```
// load fonts, images etc here

def setup()...

def draw().... 
```


Thoughts?

**Comment by ziyaointl** [comment]
I think it's ok to implement `preload` for completeness - it's easy to implement (I don't think we need to do anything extra for async calls) and does not incur much of a performance cost, but I agree that it could be deferred to future releases.

**Comment by tushar5526** [comment]
I have made `implementing preload` a good first issue for folks in the community. It would not affect `loadFont` and other APIs so I can continue with other implementations.

**Comment by tushar5526** [comment]
Turns out `preload` is needed because a different `load_font` will depend upon the `current renderer` and we have to wait till `run()` is called and `p5.renderer` is assigned.

**Comment by tushar5526** [comment]
Closing this issue.
