### ISSUE TITLE
P5 fails to install on M1 Mac

### ISSUE THREAD

**Issue by weschao** [p5py/p5#384]
MacOS Monterey 12.4, Python 3.10.6

pip3 install p5 fails, with about 2000 lines of errors, ending with:

ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

I suspect the error is that p5 requires numpy 1.18.5, but it looks like M1 support for numpy wasn't introduced until 1.21.

**Comment by weschao** [comment]
Workaround:
pip install p5 (this will fail; that’s ok)
pip install numpy (this installs the latest version)
pip install freetype-py glfw pillow pyopengl-accelerate requests skia-python vispy (installs everything that comes after numpy)

**Comment by tushar5526** [comment]
Can you try installing it from `GitHub` directly?  We have updated the dependency but a release is yet to be made.

**Comment by weschao** [comment]
Sure, happy to try. How do I install it from Github, though? The installation instructions link directs me to use pip install.

**Comment by tushar5526** [comment]
You can clone the repo and do `pip install .` in the cloned repo directory or you could use `pip install git+https://github.com/p5py/p5.git#egg=p5`. I would also recommend you to use `virtual environments` in python if you are new to it.

**Comment by ahdistefano** [comment]
> You can clone the repo and do `pip install .` in the cloned repo directory or you could use `pip install git+https://github.com/p5py/p5.git#egg=p5`. I would also recommend you to use `virtual environments` (you can google about it) in python if you are new to it.

Thanks, that was definitely it. I was having all sort of errors trying to install 0.8.0 in Windows, installing p5 through the mentioned command worked.

**Comment by tushar5526** [comment]
@ahdistefano 
Yes, we will make the new release soon once some issues for MAC are fixed here. Also, do try the new 2D renderer and feel free to open an issue if you face any bugs!

**Comment by Zhu-Aemon** [comment]
thanks! `pip install git+https://github.com/p5py/p5.git#egg=p5` works for me on my M1 macOS Ventura MacBook Ai

> You can clone the repo and do `pip install .` in the cloned repo directory or you could use `pip install git+https://github.com/p5py/p5.git#egg=p5`. I would also recommend you to use `virtual environments` (you can google about it) in python if you are new to it.

**Comment by tushar5526** [comment]
With the new release, one can just do a `pip install p5` now.
