### ISSUE TITLE
Release v0.8.1

### ISSUE THREAD

**Issue by tushar5526** [p5py/p5#397]
This issue will be used to track the TODOs for the new release. 

- [x] Increment the version number in setup.py
- [ ] Create a new tag with that version
- [x] Write some update logs summarizing the updates since last update, include this in both the p5py docs and the github release note
- [x] Create a new release on Github
- [ ] Create a new release on pypi

**Comment by tushar5526** [comment]
This release is onto halt until this issue get solved https://github.com/mcfletch/pyopengl/issues/78

**Comment by tushar5526** [comment]
@ziyaointl can you think of any workarounds ?

**Comment by ziyaointl** [comment]
I wonder if we could omit the `PyOpenGL_Accelerate` dependency until it gets updated on pypi since it isn't strictly required for pyopengl to work. We should test the performance implication of removing it though.

**Comment by tushar5526** [comment]
The accelerate project was last updated on Feb'22, so it seems there is a high chance that it might get updated. I am thinking of omitting it for now and adding a note for the 3D renderer for users to install if they want better performance for the time being.
