### ISSUE TITLE
Error while installing p5 | Add support for python 3.11

### ISSUE THREAD

**Issue by maksim10411072** [p5py/p5#409]
**Describe the bug**
when I try to install this library via` pip install p5` I get an error about Pillow installation failure, but I already have the latest version of Pillow installed
**To Reproduce**
run `pip install p5`

**Expected behavior**
p5 will install normally

**Screenshots**
![image](https://user-images.githubusercontent.com/99991427/206870232-d05bdacd-d2e9-4d42-ac1b-62efdd81dfe7.png)
![image](https://user-images.githubusercontent.com/99991427/206870298-a61d2b21-1000-48ae-b966-4c72d6d65749.png)
![image](https://user-images.githubusercontent.com/99991427/206870484-3188be38-a598-4f77-8c50-6707a5bfd464.png)

**System information:**
 - p5 release (version number or latest commit): 0.8.1
 - Python version: 3.11
 - Operating system: Windows 10 x64

**Additional context**
none

**Comment by tushar5526** [comment]
Hey, p5 is yet to release support for 3.11 use python <= 3.10

**Comment by tushar5526** [comment]
This will require setting up GHAs for python 3.11 and testing everything.

**Comment by adesh1998** [comment]
Is this issue solved because i am able to run command perfectly fine using python 3.11

**Comment by tushar5526** [comment]
Yes, it could be working. I will be closing this after the GHAs are migrated to 3.11 as well.

**Comment by tushar5526** [comment]
Closed by #461

**Comment by stu303** [comment]
requirements.txt still targets Pillow==9.0.1 which fails on 3.11 on windows.
