### ISSUE TITLE
Question: Shouldn't `pip install p5py` get you PyOpenGL?

### ISSUE THREAD

**Issue by villares** [p5py/p5#410]
I have the impression that after `pip install p5py` I didn't get `PyOpenGL`.

So I did install PyOpenGL and everything worked. Was this a fluke, or something on my system?
If this is not a mirage, if this is by design, could it be changed so that installation for beginners is easier?

I'm using Manjaro Linux.

**Comment by tushar5526** [comment]
We have ommited `pyopengl-accelarate` but pyopengl should be there. See https://github.com/p5py/p5/issues/397

**Comment by tushar5526** [comment]
Closing this issue. Feel free to open it back if you have any doubts.
