### ISSUE TITLE
Mouse click not working

### ISSUE THREAD

**Issue by someRandomCoder7** [p5py/p5#42]
**Test script:**

```python
# put your test script here
from p5 import *
# Example sketch on homepage
```

**Expected behavior:**
Example sketch on homepage

**Actual behavior**
Red circles aren't drawn when I click.

**Errors produced (if any):**
No errors produced.

**p5 version:**
0.3.0a2

**Python version:**
Python 3.6

**Operating System:** 
Windows 10

**Comment by jeremydouglass** [comment]
Perhaps close due to non-response.

**Comment by abhikpal** [comment]
That sounds reasonable, actually. Will open again if other people notice the same / there is some response here.
