### ISSUE TITLE
Inconsistency between mouse_is_pressed boolean and mouse_clicked function

### ISSUE THREAD

**Issue by swirly** [p5py/p5#441]
**Describe the bug**
the mouse_button does not behave correctly when using mouse_clicked

code to reproduce :
```python
from p5 import *

def setup():
   size(100, 100)
   fill(0)

def draw():
    background(204)
    if mouse_is_pressed:
       colorize()
    rect((25, 25), 50, 50)

def colorize():
    if mouse_button == "LEFT":
      fill(0)
    elif mouse_button == "RIGHT":
      fill(255)
    else:
      fill(126)

if __name__ == '__main__':
   run()
``` 
works correctly. Left click => black, right click => white, central click => gray

```python
from p5 import *

def setup():
   size(100, 100)
   fill(0)

def draw():
    background(204)
    rect((25, 25), 50, 50)

def mouse_clicked():
    if mouse_button == "LEFT":
      fill(0)
    elif mouse_button == "RIGHT":
      fill(255)
    else:
      fill(126)

if __name__ == '__main__':
   run()
```
Does not work.  Mouse_button seems undefined in mouse_clicked function and only gray is selected, whatever the click button is.

**To Reproduce**
Just use the code above

**Expected behavior**
The two code should behave the same

**System information:**
 - p5 release (version number or latest commit): latest pip version
 - Python version: 3.9
 - Operating system: Mac OS X

**Comment by tushar5526** [comment]
Hi @swirly, this was rather a quick fix. Fixed it for both "skia" and "vispy" renderers.
