### ISSUE TITLE
pip cant install p5

### ISSUE THREAD

**Issue by luck351** [p5py/p5#468]
**Describe the bug**
ill run "pip install p5" and get some errors

![image](https://github.com/p5py/p5/assets/158477963/acba50f0-a5ae-4f32-9418-23eb0181e667)
![image](https://github.com/p5py/p5/assets/158477963/c80821c1-b04a-4093-8912-9944dc739f7d)

**System information:**
 - p5 release (version number or latest commit):
 - Python version:3.12
 - Operating system: win 10 64x

please help

**Comment by tushar5526** [comment]
Please try python <= 3.11

**Comment by luck351** [comment]
could only download with python 3.10 because of pillow
![image](https://github.com/p5py/p5/assets/158477963/4eb53913-9072-46c2-9fc3-30f007b4d705)
