### ISSUE TITLE
key variable not working

### ISSUE THREAD

**Issue by BarbaraAlmeida** [p5py/p5#47]
I can't use `key` as showed in the [docs](https://p5.readthedocs.io/en/latest/reference/input.html#key), the comparison always returns `false`.
When I tried to print `key` it shows it isn't the key pressed, but [pyglet.window.key](https://pythonhosted.org/pyglet/api/pyglet.window.key-module.html).

Looking at https://github.com/p5py/p5/blob/master/p5/sketch/events.py I was able to get the key using `event.key` (but it's always uppercase) or `builtins.key`. 

**Test script:**

```python
from p5 import *

def key_pressed(event):
    print('key: {}'.format(key));
    print('event.key: {}'.format(event.key));
    print('builtins.key: {}'.format(builtins.key));

run()

```

**Actual behavior**
When I press `a`:
```
key: <module 'pyglet.window.key' from '/home/barbara/.local/lib
/python3.5/site-packages/pyglet/window/key.py'>
event.key: A
builtins.key: a
```

**p5 version:** 0.3.0a2
**Python version:** 3.5.2
**Operating System:**  Ubuntu 16.04.4 LTS

**Comment by abhikpal** [comment]
Yes! I can reproduce this, using ```key``` doesn't seem to work for me as well :( But I'll take a look and see what needs to be done. Since it's possible to retrieve the key using ```event.key``` I'm assuming p5 isn't setting the global ```key``` variable when it sets ```event.key```.

Thanks a lot for pointing this out!
