### ISSUE TITLE
Unable to run custom setup and draw

### ISSUE THREAD

**Issue by martynvdijke** [p5py/p5#471]
**Describe the bug**
I want to trigger my own function  for setup and drawing.
however this does not seem to work as my code below crashed at
`
  File ".venv/lib/python3.11/site-packages/p5/sketch/userspace.py", line 260, in size
    p5.sketch.size = (builtins.width, builtins.height)
    AttributeError: 'NoneType' object has no attribute 'size'
`
It seems that on this `size()` there is no sketch attribute to p5, but I have tried digging into but cant seem to understand why that is the case ?

**To Reproduce**
```python
import p5

def setup():
   p5.size(128,64)
   p5.no_loop()
   p5.fill(0)

def draw():
   p5.background(204)
   p5.text("LAX", (0, 40))
   p5.text("LHR", (0, 70))
   p5.text("TXL", (0, 100))
   
p5.run(sketch_setup=setup(),sketch_draw=draw())
```

**Expected behavior**
To be able to draw using custom defined function.

**System information:**
 - p5 release (version number or latest commit):
 - Python version: 3.11
 - Operating system: Arch Linux

**Comment by tushar5526** [comment]
Hi @martynvdijke, it should be

```python
p5.run(sketch_setup=setup,sketch_draw=draw)
```

You don't have to call the function while passing it. You can also use p5py like this

```python
from p5 import *


def setup():
    size(128, 64)
    no_loop()
    fill(0)


def draw():
    background(204)
    text("LAX", (0, 40))
    text("LHR", (0, 70))
    text("TXL", (0, 100))

# experimental but better 2D renderer
run(renderer='skia')
```

**Comment by martynvdijke** [comment]
Thank you that works !
