### ISSUE TITLE
Can't install p5 package through pip install

### ISSUE THREAD

**Issue by CasparB** [p5py/p5#48]
**Script:**

$ pip install numpy
$ pip install p5 --user

**Expected behavior:**

The numpy and p5 packages are installed without issue

**Actual behavior**

The numpy package installs but the p5 package does not and returns an error.

**Errors produced (if any):**

```
$ pip install p5 --user
Collecting p5
  Using cached https://files.pythonhosted.org/packages/3b/fd/16ab17979a0c47a46d45a76d2821de512fdcccf686c0ca63b142b362ef64/p5-0.3.0a2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_j/6bwypd896z95ndkxjfpr1rbh0000gn/T/pip-install-0UM8cd/p5/setup.py", line 20, in <module>
        with open(os.path.join(here, 'p5', '__version__.py'), 'r', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_j/6bwypd896z95ndkxjfpr1rbh0000gn/T/pip-install-0UM8cd/p5/
```

**Additionally...**

I tried to download the package from the GitHub page and drop it in /usr/local/lib/python3.6/site-packages/ , but whenever I run python3 (name of test file) it doesn't recognise script that is part of the library, such as run() at the end of the supplied example files (I've tried multiple example files, all of which don't work)

**Python version:**

V 3.6 is installed on my computer.

**Operating System:** 

macOS Sierra

**Comment by abhikpal** [comment]
Python environments [often do funny things,](https://xkcd.com/1987/) and your ```pip``` command could be defaulting to Python 2 (maybe?).

Can you try running ```pip -V``` to see the version of ```pip``` your computer is using?

**Comment by CasparB** [comment]
Hi Abhikpal, 
I installed the p5 package through the following command:

```
$ pip3.6 install p5 --user
```

And my packages library contains the p5 folders. However, the following code still returns the error `name 'run' is not defined`

Here's the test code:

```
from p5 import *

def setup():
   size(640, 360)
   no_stroke()
   background(204)

def draw():
   if mouse_is_pressed:
       fill(random_uniform(255), random_uniform(127), random_uniform(51), 127)
   else:
       fill(255, 15)

   circle_size = random_uniform(low=10, high=80)

   circle((mouse_x, mouse_y), circle_size)

def key_pressed(event):
   background(204)

run()
```

**Comment by abhikpal** [comment]
Okay, this is interesting. Can you please try running this on the Python interpreter:

```python
>>> import p5
>>> 'run' in dir(p5)
```

**Comment by CasparB** [comment]
Running the above in IDLE or Terminal looks like this for me:

```python
>>> import p5
>>> 'run' in dir(p5)
True
>>> 
```

So, the p5 package seems to import fine, but when I run the second line it returns `True` and opens up the Python rocket ship for GUI's in my dock, which bounces indefinitely, and I have to force quit it because it won't respond.

I've tried two things:

1. Uninstalling and reinstalling p5 via `$ pip3.6 uninstall p5` followed by `$ pip3.6 install p5 --user`, which did nothing to change the issue.
2. Changing the preferences on the Python Launcher so 'Settings for file type' is set to Python GUI script, which doesn't change the issue either.

**Comment by CasparB** [comment]
Fixed the issue through a complete reinstall of the p5, numpy, pyopengl and pyglet libraries. The window now appears, however after a few seconds the circles start to appear much more slowly and the frame eventually freezes.

**Comment by abhikpal** [comment]
Ahh. okay. I guess the initial failed Python 2.7 install must be lying around somewhere!

Since we're done figuring this out, I'm closing this.... feel free to open other issues if you run into some odd behavior :)
