### ISSUE TITLE
Display a video

### ISSUE THREAD

**Issue by johhnry** [p5py/p5#51]
Hi guys,

Just wanted to know if it was possible to display a video with p5py or the Video library isn't implemented yet.

Thanks

**Comment by johhnry** [comment]
@abhikpal Is it possible ?

**Comment by abhikpal** [comment]
It's not possible to display videos on p5 yet and there's also no Video library.

**Comment by johhnry** [comment]
Ok thanks for replying 👍

**Comment by aceking007** [comment]
@abhikpal Hi! I am interested in adding a Video library to p5py if it has not been done yet. I would also like to work on this project as part of GSoC 2021. Would you be interested in mentoring this year for the same? Or can I contact anyone else for the same?
