### ISSUE TITLE
GLFW not found error

### ISSUE THREAD

**Issue by villares** [p5py/p5#53]
**Test script:**

```python
# from the examples
from p5 import *

def setup():
    size(640, 360)
    no_stroke()
    background(204)
    circle((100, 100), 100)

def draw():
    circle((150, 100), 100)

run()

```

**Expected behavior:**
Basic example code
**Actual behavior**
Does not start
**Errors produced (if any):**
RuntimeError: Could not import backend "Glfw":
GLFW library not found
**p5 version:**
 0.4.0a1.dev2
**Python version:**
Python 3.6.1
**Operating System:** 
macOS

![screen shot 2018-07-21 at 11 45 00 am](https://user-images.githubusercontent.com/3694604/43036682-76bffc42-8cdc-11e8-9c38-29dbec0328dd.png)

I'm testing on Thonny.org IDE, a beginner's IDE that comes with a Python 3.6.1 environment. 
I have done a `pip3 install numpy` and `pip3 install p5 --user` as recommended and all the dependencies seem installed alright.

**Comment by abhikpal** [comment]
Have you installed GLFW for your operating system (the [installation page](http://p5.readthedocs.io/en/latest/install.html#prerequisites-glfw) has instructions)?

**Comment by villares** [comment]
Hmmm, I thought I had installed it earlier on (previously p5 was opening a window). But then I ran the `brew` thing today and lo and behold:
![screen shot 2018-07-21 at 4 45 30 pm](https://user-images.githubusercontent.com/3694604/43039537-dffc1aa0-8d05-11e8-8d24-d7f0dbcf4408.png)
(I will try a brew upgrade now and post results)

**Comment by villares** [comment]
Well, no more `GLFW library not found` warning, but something is not quite right...

![screen shot 2018-07-21 at 5 35 06 pm](https://user-images.githubusercontent.com/3694604/43039856-734be582-8d0c-11e8-97cf-3b2a82a08e4b.png)

Should I open another issue?

**Comment by abhikpal** [comment]
> Well, no more GLFW library not found warning, but something is not quite right...

hmm.. this is quite odd..

> Should I open another issue?

Might be a good idea, actually. I'm closing this as the installation related issue sorted itself out.

**Comment by villares** [comment]
Thanks! I'll try some restarts and re-installs later, to see if it persists, then I can open a new appropriate issue.

**Comment by paulossa** [comment]
```bash
paulo@y50 MINGW64 ~/workspace/iapy
$ python sketch.py
Traceback (most recent call last):
  File "sketch.py", line 1, in <module>
    from p5 import *
  File "C:\Users\paulo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\p5\__init__.py", line 19, in <module>
    from .sketch import *
  File "C:\Users\paulo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\p5\sketch\__init__.py", line 19, in <module>
    vispy.use('glfw')
  File "C:\Users\paulo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\vispy\util\wrappers.py", line 96, in use
    use_app(app)
  File "C:\Users\paulo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "C:\Users\paulo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\vispy\app\application.py", line 49, in __init__
    self._use(backend_name)
  File "C:\Users\paulo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\vispy\app\application.py", line 223, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "Glfw":
GLFW library not found
```

I just installed python and p5 through pip. 

Is it a bug or smth?

**Comment by abhikpal** [comment]
@paulossa I'm assuming you're using windows, did you install GLFW?

**Comment by mhlinder** [comment]
I am using OS X, however, I get the same error:

```
Python 3.6.0 |Anaconda 4.3.1 (x86_64)| (default, Dec 23 2016, 13:19:00)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import p5
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-85b334b3a19e> in <module>()
----> 1 import p5

/Users/henry/anaconda3/lib/python3.6/site-packages/p5/__init__.py in <module>()
     17 #
     18
---> 19 from .sketch import *
     20 from .core import *
     21 from .pmath import *

/Users/henry/anaconda3/lib/python3.6/site-packages/p5/sketch/__init__.py in <module>()
     17 #
     18 import vispy
---> 19 vispy.use('glfw')
     20
     21 from .userspace import *

/Users/henry/anaconda3/lib/python3.6/site-packages/vispy/util/wrappers.py in use(app, gl)
     94     if app:
     95         from ..app import use_app
---> 96         use_app(app)
     97
     98

/Users/henry/anaconda3/lib/python3.6/site-packages/vispy/app/_default_app.py in use_app(backend_name, call_reuse)
     45
     46     # Create default app
---> 47     default_app = Application(backend_name)
     48     return default_app
     49

/Users/henry/anaconda3/lib/python3.6/site-packages/vispy/app/application.py in __init__(self, backend_name)
     47         self._backend_module = None
     48         self._backend = None
---> 49         self._use(backend_name)
     50
     51     def __repr__(self):

/Users/henry/anaconda3/lib/python3.6/site-packages/vispy/app/application.py in _use(self, backend_name)
    221                 if not try_others:
    222                     # Fail if user wanted to use a specific backend
--> 223                     raise RuntimeError(msg)
    224                 elif key in imported_toolkits:
    225                     # Warn if were unable to use an already imported toolkit

RuntimeError: Could not import backend "Glfw":
GLFW library not found
```

**Comment by abhikpal** [comment]
Did you install GLFW using brew or something similar?

**Comment by bobthesnek63** [comment]
I'm having the same problem as well. I have added GLFW to my user path variable and downloaded all the dependencies but still receive the same problem where it cannot find the GLFW module. I also tried pip install glfw, which does download the package to site-packages, but still doesn't work

**Comment by Mayaank2004** [comment]
I faced the same issue ... solved by copying the main  `glfw` folder to the `Program Files` (or Program Files (x86) if you are on 32 bit).  
and renaming the `lib-vc2012` in the `glfw ` to `lib`
