### ISSUE TITLE
set font and display text

### ISSUE THREAD

**Issue by kurakuradave** [p5py/p5#55]
Hi, really excited to have found p5. However, is there a way to set some font and draw some text on the sketch yet?  I searched through the code but couldn't find anything around this. Looking forward to see this implemented - Thanks!

**Test script:**

```python
# put your test script here
from p5 import *
text("Hello P5!", 30, 50)
```

**Expected behavior:**
the text "Hello P5!" displayed on the sketch at coordinate( 30,50 )

**Actual behavior**
Error

**Errors produced (if any):**
Traceback (most recent call last):
  File "test_some_text.py", line 2, in <module>
    text("hello P5!", 30, 50)
NameError: name 'text' is not defined

**p5 version:**
0.4.0a1.dev2

**Python version:**
3.5.2

**Operating System:** 
Ubuntu 16.04 64 bit

**Comment by abhikpal** [comment]
Hey, there's some minimal font support in the latest developmental code! We're in the process of writing some documentation for it, but you might want to start playing around with it now as well. Here's a minimal sketch:

```python
from p5 import *

def draw():
    text("Hello world", (10, 50))

run()
```

**Comment by mazunki** [comment]
This issue can be closed.
