### ISSUE TITLE
title() sometimes only sets the first character

### ISSUE THREAD

**Issue by mark-summerfield** [p5py/p5#63]
**Test script:**

```python
# put your test script here
from p5 import *
def setup():
    title('My Sketch')

def draw():
    background(245, 245, 245)

run()
```

**Expected behavior:**
I expect the title to show 'My Sketch'.
**Actual behavior**
The title is shown as 'M'.
**Errors produced (if any):**

**p5 version:**
0.4.0a1.dev2
**Python version:**
3.7.0
**Operating System:** 
Ubuntu 16.04.5 LTS (64-bit)

**Comment by abhikpal** [comment]
Hm. I've noticed this as well. Don't really know how to approach this though. I'll try to take a look nonetheless.

Thanks for pointing this out : )

**Comment by Gotham13121997** [comment]
Hello, I found a workaround by passing the title as title.encode('utf-8') the whole title is coming up. I am not sure wether this is a problem with vispy or we need to make changes in p5py so I have raised an issue on vispy about this https://github.com/vispy/vispy/issues/1533 .

**Comment by Gotham13121997** [comment]
@abhikpal I have opened a pr in vispy https://github.com/vispy/vispy/pull/1534 .  I think they will merge it. But it will come in next release only. Should I implement it in p5 ??

**Comment by Gotham13121997** [comment]
@abhikpal its been merged in vispy. You can close this as vispy issue

**Comment by abhikpal** [comment]
@Gotham13121997, thanks!
