### ISSUE TITLE
Stroke on overlaping shape

### ISSUE THREAD

**Issue by l-atome** [p5py/p5#67]
**Describe the bug**
When two 2d figure overlap themself, appaer the stroke of the two objects ...

![sans titre](https://user-images.githubusercontent.com/11404523/44641149-ddd25280-a9c5-11e8-9b18-de18ff527e02.png)

I don't know if it's a bug or not .. I found an article about the same subjet for "p5js"
https://github.com/processing/p5.js/issues/2938

**To Reproduce**
This is the code used : 
```python
from p5 import *

pos=0

def setup():
    size(400,400)

def draw():
    global pos;
    background(125)
    fill(255);
    rect((20,0),30,400)
    rect((200,0),100,100)
    ellipse((200,300),100,100)
    
    # Trace du rectangle flottant
    rect((pos,pos),50,50)
    pos=pos+1
    if pos>350:
        pos=0;
```

**System information:**
 - p5 release 0.5.0
 - Python version: 3.6
 - Operating system: Ubuntu 18.04

**Comment by piotrenewicz** [comment]
This is more of a feature missing. It's the lack of z-ordering in this port. That means that everything drawn will appear stacked vertically in the same order as it was drawn. It doesn't sound like an issue, but combined with the fact that strokes are drawn last, at the very end of draw(). They are on top of everything.

**Comment by abhikpal** [comment]
@l-atome, thanks for pointing this out. @piotrenewicz is correct, right now the strokes get pooled together and get drawn at the end of the draw loop.

This does need some work to make it consistent with Processing (JAVA).

**Comment by parsoyaarihant** [comment]
This issue has been resolved in the development branch, it will be merged into the master branch soon.
