### ISSUE TITLE
The command-line quit when i close window

### ISSUE THREAD

**Issue by l-atome** [p5py/p5#68]
**Describe the bug**
When I execute a script in command-line "exec(open(script.py).read())", the module "p5" close my command-prompt/python ...
With the pyzo IDE, I need relaunch manually the kernel to execute again the script

**To Reproduce**
Steps to reproduce the behavior (if applicable)

**Expected behavior**
The use of the "p5" will be more "confortable" if we don"t need to lauch at each time a new "kernel" python

**Screenshots**
You can see a little video screen capture below
[a.zip](https://github.com/p5py/p5/files/2322462/a.zip)

**System information:**
 - p5 release : 0.5.0
 - Python version: 3.6
 - Operating system: Ubuntu 18.04

**Comment by abhikpal** [comment]
Closing this for now as the behavior is as expected and I can't think of a reasonable workaround. Feel free to reopen, if you have additional comments on this.
