### ISSUE TITLE
pmouse_x and mouse_x behavior on mouse pressed

### ISSUE THREAD

**Issue by armansansd** [p5py/p5#71]
Hello everyone, 

When I print ```mouse_x``` and ```pmouse_x``` on ```mouse_is_pressed```, 
mouse_x and pmouse_x are equal, why ? 
```python
if mouse_is_pressed:
        print (mouse_x, pmouse_x)
```

But when i'm not use using  this condition, mouse and pmouse are different (as expected) 

Any clues ? 

Cheers, 

[ p5 latest commit,  Python 3, Archlinux]

**Comment by Sushanti99** [comment]
I think this has something to do with pmouse_x and pmouse_y not updating everytime the mouse is pressed whereas inside other functions, they're updated in every frame.

**Comment by abhikpal** [comment]
> I think this has something to do with pmouse_x and pmouse_y not updating everytime the mouse is pressed whereas inside other functions, they're updated in every frame.

Exactly! 

I hope that sorts it out, I'm closing this now.
