### ISSUE TITLE
Impossible to use _get_pixel() after filter("gray")

### ISSUE THREAD

**Issue by l-atome** [p5py/p5#78]
**Describe the bug**
A bug in use of "_get_pixel()" with an PImage after a gray filter

**To Reproduce**
```python
from p5 import *
im1 = load_image("a.jpg");
def setup():
   size(*im1.size);
   no_loop();
def draw():
    im1.filter('gray');
    im1.load_pixels();
    a=im1._get_pixel((0,0));
```

**Additional context**
It seems to come from "code/image.py" ... if you change the line
```python
            col = color.Color(*self._img.getpixel((px, py)))
```
to
```python
            col = color.Color(self._img.getpixel((px, py)))
```
it works but i don't understand why?_

**Comment by abhikpal** [comment]
In general, one should avoid using functions/methods that begin with `_` as they are usually meant for "internal" use (see "Naming styles" here: https://www.python.org/dev/peps/pep-0008/). The proper way to read pixel values is to treat the image like a 2d array and then index into it (see example here: https://github.com/p5py/p5-examples/blob/master/reference/image/pimage/get_1.py)

**Comment by abhikpal** [comment]
Closing this as `_get_pixel()` isn't part of the public API and is meant for internal use only.
