### ISSUE TITLE
run() gives error 'module' object has no attribute 'isclose'

### ISSUE THREAD

**Issue by timo-mart** [p5py/p5#84]
**Describe the bug**
I cant run sketches because at run() the program gives an error:
```
Exception has occurred: AttributeError
'module' object has no attribute 'isclose'
```
I think I have installed GLFW correctly since I don't get error at `from p5 import *` anymore

**Comment by dbhavsar76** [comment]
@timo-mart Please provide a test script or a sketch that you tried to run and gave the error.

**Comment by timo-mart** [comment]
This happens with any script. I've used one of the example sketches:
```
from p5 import *

def setup():
  size(640, 360)
  no_stroke()
  background(204)

def draw():
  if mouse_is_pressed:
    fill(random_uniform(255), random_uniform(127), random_uniform(51), 127)
  else:
    fill(255, 15)

circle_size = random_uniform(low=10, high=80)

circle((mouse_x, mouse_y), circle_size)

def key_pressed(event):
  background(204)

run()
```
as well as a pretty much blank sketch:
```
from p5 import *

def setup():
  size(500, 500)

def draw():
  background(204)

run()
```

**Comment by dbhavsar76** [comment]
then, can you provide full error log with traceback? And also which os you are running and python version too.

**Comment by redfood** [comment]
I believe I saw this error.  math.isclose() was added in python 3.5.  For me, upgrading from 3.4 to a newer version of python fixed the problem.

**Comment by abhikpal** [comment]
> `math.isclose()` was added in python 3.5. 

Correct. If there's a need we can find a way around this, but for now I'll just mark this as closed. @dbhavsar76, thanks for helping sort this out!
