### ISSUE TITLE
name 'run' is not defined in mac OS sierra python3 or regular python after following install instructions

### ISSUE THREAD

**Issue by GustavoPT** [p5py/p5#85]
**Describe the bug**
name 'run' is not defined in mac OS sierra python3 or regular python after following install instructions
**To Reproduce**
Steps to reproduce the behavior (if applicable)
I followed the installation instructions and getting the error run is not defined after 
running the beginners script

**Expected behavior**

**Screenshots**

**System information:**
 - p5 release (version number or latest commit):
 - Python version: 3 or 2.7 tried both 
 - Operating system:Mac OS High sierra

**Additional context**

**Comment by lwrd** [comment]
Problem was solved after simple moving the project folder in different place. Before it was in Documents folder.

**Comment by akka47** [comment]
+1. Also having this error.

**Comment by parsoyaarihant** [comment]
@akka47 can you tell which version of `vispy` is installed using `pip show vispy`

**Comment by GustavoPT** [comment]
Hello 
Wow been awhile, I just an email of this since someone posted lol, i forgot what I did but the issue somewhat solved since j got a snippet to display itself I forgot why tho.should I close this issue?
