### ISSUE TITLE
no_loop doesn't work in setup

### ISSUE THREAD

**Issue by redfood** [p5py/p5#88]
**Describe the bug**
No loop doesn't do anything when called in setup.

**To Reproduce**
Call no_loop in setup.

For example:
``` py
from p5 import *

def setup():
    size(500, 100)
    no_loop()

x= 0

def draw():
    global x
    ellipse((x,50), 100,100 )
    x +=1

run()
```

**Expected behavior**
We would see a half circle on the left edge of the window because the ellipse would be called once with an x of 0.  

**Screenshots**
Instead, we see the ellipse animate across the screen.  E.G:

<img width="612" alt="screen shot 2019-01-15 at 5 51 35 pm" src="https://user-images.githubusercontent.com/2761071/51215252-5478d980-18ee-11e9-8a47-d6cce23286b2.png">

**System information:**
 - p5 release (version number or latest commit): 0.7.2
 - Python version: Python 3.7.1
 - Operating system: MacOS 10.13.6

(Same problem found under ubuntu)

**Additional context**

**Comment by abhikpal** [comment]
Ah! Thanks for pointing this out. This indeed seems to be a bug!

**Comment by vaishnavsm** [comment]
Found out the error:
`if self.looping or self.redraw:
                builtins.frame_count += 1
                if not self.setup_done:
                    self.setup_method()
                    self.setup_done = True
                    self.show(visible=True)
                    self.redraw = True
                    self.looping = False
                else:
                    self.looping = True
                    self.draw_method()
                    self.redraw = False`
1) Setup: looping is True, setup_method sets looping to False, redraw is set to True by the if block
2) Loop enters due to redraw, elif block sets looping to True.

Will fix, test and write a PR soon.

**Comment by vaishnavsm** [comment]
Quick fix, remove the changes to `looping` in this block. It is logically not needed, and seems to reflect the required behavior. Will test a bit more and then add a PR.
