### ISSUE TITLE
p5 doesn't exit if there is a bug in draw or setup.

### ISSUE THREAD

**Issue by redfood** [p5py/p5#89]
**Describe the bug**
If you have an error in your program you would expect for python to print the error and to exit.  Instead, if you have an error in `draw` or `setup` p5 doesn't exit. It prints the error and then repeatedly prints `ERROR: Invoking <bound method Sketch.on_timer of <Sketch (Glfw) at 0x10fb3ed68>> for Event`.  This is true even if you have called `no_loop()`

**To Reproduce**
Introduce an error into `setup` or `draw`.  e.g.
``` py
from p5 import *

def setup():
    size(100,100)

def draw():
    no_loop()
    typo()

run()
```

**Expected behavior**
You would expect the program to exit with an error message.

**System information:**
 - p5 release (version number or latest commit): 7.2
 - Python version: 3.7.1
 - Operating system: macOS 10,13.6

**Comment by dbhavsar76** [comment]
I think this is GLFW or Vispy's problem.

**Comment by abhikpal** [comment]
> I think this is GLFW or Vispy's problem.

Correct. I can't think of any way we can handle this from within p5 as everything inside draw/setup is ultimately sent to vispy (and hence GLFW). I'm closing this now, but if someone has ideas, feel free to open this.
