### ISSUE TITLE
Sketch does not cover the entire window on retina displays.

### ISSUE THREAD

**Issue by abhikpal** [p5py/p5#9]
**Test script:** [p5-examples/basics/color/color_variables.py](https://github.com/p5py/p5-examples/blob/master/basics/color/color_variables.py)

**Expected behavior:**
![screenshot from 2017-08-16 04-16-44](https://user-images.githubusercontent.com/3626001/29339924-3e9d5362-823a-11e7-8e11-dc29c82dd265.png)

**Actual behavior**

<img width="645" alt="screen shot 2017-08-04 at 11 58 01 am" src="https://user-images.githubusercontent.com/3626001/29339941-4b7566ec-823a-11e7-8533-57e866d5b403.png">

**Errors produced (if any):** None

**p5 version:** 2b96dfc1d2126867e70bc727d0cc7ffc5da8eabc

**Python version:** Python 3.6
**Operating System:** Mac OS

**Comment by marcrleonard** [comment]
I can confirm this is still the case. I assume there is not a DPI function like there is in p5.js?

**Comment by marcrleonard** [comment]
I took a look at how p5.js did this, and it wasn't a feature like I original thought. They just add a multiplier in the dom. I was able to fix it by basically adding a `density()` function in setup. After digging deep into how pyglet is 'grabbing' the resolution, I think it's impossible to get the native resolution (it's .5 the actual resolution). But! Funny enough, the actual pixel rendering is correct. So it's just the pyglet window that gets scaled down to the proper size. I'll attempt to do a pull request later (never done one before!)

**Comment by swirly** [comment]
issue still revelant for me. Anaconda python last version (python 3.7), p5py, vispy and pyglet installed with pip
```
# pip install p5py pyglet vispy
Requirement already satisfied: p5py in /Users/laurent/anaconda3/lib/python3.7/site-packages (1.0.0)
Requirement already satisfied: pyglet in /Users/laurent/anaconda3/lib/python3.7/site-packages (1.4.4)
Requirement already satisfied: vispy in /Users/laurent/anaconda3/lib/python3.7/site-packages (0.6.1)
```
