### ISSUE TITLE
arc outline shows up as line in corner of window

### ISSUE THREAD

**Issue by MHC-DS** [p5py/p5#90]
**Describe the bug**

Often when you draw an arc it is missing an outline and there is a smudge in the upper left-hand corner of the window instead.

**To Reproduce**
``` py
def setup():
    p5.size(200, 200)

def draw():
    p5.stroke(255,0,0)
    p5.arc( (100,100), 100, 100, 0, 1.5 * p5.PI)

p5.run()
```

**Expected behavior**

The arc would be drawn with an outline.  There should not be a red or black line in the corner.

**Screenshots**
<img width="312" alt="image" src="https://user-images.githubusercontent.com/25232521/52231448-fe151000-2887-11e9-8d5b-6800de12d69b.png">

**System information:**
 - p5 release (version number or latest commit): Version: 0.5.0
 - Python version: 3.7.1
 - Operating system: MacOS 10.13.6

**Comment by mariekeane** [comment]
I am experiencing the same issue, has there been any progress on this?

**Comment by jeremydouglass** [comment]
Looks like arc() is here:

https://github.com/p5py/p5/blob/54e7be35ee68719e7785d22854e29be5b373940e/p5/core/primitives.py#L427

...and arc() then returns an Arc(PShape), code here:

https://github.com/p5py/p5/blob/54e7be35ee68719e7785d22854e29be5b373940e/p5/core/primitives.py#L81

That line looks a bit like an x,y (or a diam,radians) instead was accidentally rendered as an x,x or an r,r. If it is 32 pixels long might be TWOPI-based somehow.

**Comment by parsoyaarihant** [comment]
This issue is fixed in develop branch. The develop branch will be merged into master soon.
