### ISSUE TITLE
Arc does not render correctly with transparency

### ISSUE THREAD

**Issue by redfood** [p5py/p5#91]
**Describe the bug**
If you are using a transparent fill, arcs do not render correctly.  Instead, you see a triangle and a cord of different shades.

**To Reproduce**
``` py 
from p5 import *

def setup():
    size(300,300)

def draw():
    background(0)
    no_stroke()
    fill(255, 50)
    arc( (0, 0), 2*width, 2*width, 0, PI/2)

run()
```

**Expected behavior**
You would expect to see a gray pie shape.

**Screenshots**
<img width="412" alt="image" src="https://user-images.githubusercontent.com/2761071/52458209-173deb00-2b2c-11e9-89e0-4e07f03d1c4a.png">

**System information:**
 - p5 release 0.5.0
 - Python version: 3.7.2
 - Operating system: MacOS 10.13.6

**Comment by parsoyaarihant** [comment]
This issue is fixed in develop branch. The develop branch will be merged into master soon.
