### ISSUE TITLE
beginShape() endShape()

### ISSUE THREAD

**Issue by peryvel** [p5py/p5#97]
Is there a way to do this code in p5 ?
```java
beginShape();
for(int i=0; i<20; i++){
  int y = i%2;     
  vertex(i*10, 50+y*10); 
};
endShape();
```
 I do not find beginShape() and endShape() in the documentation.

**Comment by abhikpal** [comment]
We've implemented the same functionality using context managers. So, you can do something like:
```python
s = PShape()
with s.edit():
    for i in range(20):
        v = (i * 10, 50 + y * 10)
        s.add_vertex(v)
```
See the `star.py` example here: https://github.com/p5py/p5-examples/blob/master/basics/form/star.py
